imports:
  - { resource: parameters.ini }
  - { resource: security.yml }

framework:
  #esi:             ~
  #translator:      { fallback: %locale% }
  translator: ~
  secret:          %secret%
  charset:         UTF-8
  router:          { resource: "%kernel.root_dir%/config/routing.yml" }
  form:            true
  csrf_protection: true
  validation:      { enable_annotations: true }
  templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
  session:
    default_locale: %locale%
    lifetime:       3600
    auto_start:     true

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%
  form:
    resources:
      - '::fields.html.twig'

# Assetic Configuration
assetic:
  debug:          %kernel.debug%
  use_controller: false
  filters:
    cssrewrite: ~
    # closure:
    #     jar: %kernel.root_dir%/java/compiler.jar
    # yui_css:
    #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
  dbal:
    connections:
      default:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        port:     %database_port%
        user:     %database_user%
        password: %database_password%

  orm:
    auto_generate_proxy_classes: %kernel.debug%
    entity_managers:
      default:
        connection: default
        auto_mapping: true
        mappings:
          StofDoctrineExtensionsBundle: false


stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      timestampable: true
        
# Swiftmailer Configuration
swiftmailer:
  transport:  sendmail

jms_security_extra:
  secure_controllers:  true
  secure_all_services: false

knp_menu:
  twig: true

phosh_main:
  storage_dir: %kernel.root_dir%/../photostorage
  thumbs_dir: %kernel.cache_dir%/thumbs
  order_created_from_email: %email_from%
  order_created_to_email: %email_to%

mopa_bootstrap:
  form:
    show_legend: false # default is true
    show_legend: false # default is true

fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb'
  firewall_name: main
  user_class: Phosh\MainBundle\Entity\User