# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

market_bundle:
  resource: "@EmpMarketBundle/Controller"
  type:     annotation

login:
  pattern:   /login
  defaults:  { _controller: EmpMarketBundle:Security:login }

logout:
  pattern:   /logout

login_check:
  pattern:   /login_check