security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Emp\MarketBundle\Entity\User: sha1

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      users:
        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    fos_userbundle:
      id: fos_user.user_manager

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:    ^/.*
      anonymous: ~
      form_login:
        provider: fos_userbundle
        default_target_path: /admin/posts
      logout:
        invalidate_session: true
        target: /login
      remember_me:
        key:  iadkfia~!~304-0ieefdsgdsg%%(@_(!@(13ddaadsdsaads;kwd!@@$!?093808903212dd
        lifetime: 604800 # 86400 * 7 in seconds - 24 hours

  access_control:
    - { path: ^/admin/, roles: ROLE_ADMIN }
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }