Phosh\MainBundle\Entity\Post:
  properties:
    title:
      - NotBlank: ~
      - MinLength: 3
      - MaxLength: 255
    expiredAt:
      - NotBlank: ~

Phosh\MainBundle\Entity\Product:
  properties:
    title:
      - NotBlank: ~
      - MinLength: 3
      - MaxLength: 255
    description:
      - NotBlank: ~