Phosh\MainBundle\Entity\Post:
  properties:
    title:
      - NotBlank: ~
      - MinLength: 3
      - MaxLength: 255
    expiredAt:
      - NotBlank: ~
  getters:
     descriptionOrProductFilled:
      - "True": { message: "Please add at least one product or fill description" }

Phosh\MainBundle\Entity\Product:
  properties:
    title:
      - NotBlank: ~
      - MinLength: 3
      - MaxLength: 255
    description:
      - NotBlank: ~

Phosh\MainBundle\Entity\Order:
  properties:
    customer:
      - NotBlank: ~
      - MinLength: 3
      - MaxLength: 255
    post:
      - NotBlank: ~