Phosh\MainBundle\Entity\Post:
  type: entity
  table: posts

  uniqueConstraints:
    posts_token_unique_idx:
      columns: token

  id:
    id: 
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      length: 255
    body:
      type: text
    token:
      type: string
      lenght: 255
    owner:
      type: string
      lenght: 255
    attachedPhotos:
      column: attached_photos
      type: array
    createdAt:
      column: created_at
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      nullable: true
      type: datetime
      gedmo:
        timestampable:
          on: update
    expiredAt:
      column: expired_at
      type: datetime
      nullable: true

  lifecycleCallbacks:
    preUpdate: [ calculateAttachedPhotos ]
    prePersist: [ calculateAttachedPhotos ]
