Phosh\MainBundle\Entity\Post:
  type: entity
  table: posts

  uniqueConstraints:
    posts_token_unique_idx:
      columns: token

  id:
    id: 
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      length: 255
    description:
      type: text
      nullable: true
    token:
      type: string
      lenght: 255
    createdAt:
      column: created_at
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      nullable: true
      type: datetime
      gedmo:
        timestampable:
          on: update
    expiredAt:
      column: expired_at
      type: datetime
      nullable: true

  manyToOne:
    owner:
      targetEntity: User
      joinColumn:
        name: owner_id
        referencedColumnName: id

  manyToMany:
    products:
      cascade: ["persist"]
      targetEntity: Product
      joinTable:
        name: post_products
        joinColumns:
          post_id:
            referencedColumnName: id
            onDelete: "CASCADE"
        inverseJoinColumns:
          product_id:
            referencedColumnName: id
            onDelete: "CASCADE"